port_profiles:
  TENANT_A:
    mode: trunk
    vlans: 110-150
  TENANT_A_B_C:
    mode: trunk
    vlans: 110-150,210-211,310-311
  TENANT_B:
    mode: trunk
    vlans: 210-211
  TENANT_C:
    mode: trunk
    vlans: 310-311

  # TENANT_A_OPZone:
  #   mode: access
  #   vlans: "110"

  # TENANT_A_ALL:
  #   mode: trunk
  #   vlans: "120-130,160-161"

servers:
  centos:
    adapters:
    - profile: TENANT_A_B_C
      server_ports:
      - Eth1
      switch_ports:
      - Ethernet3
      switches:
      - DC1-L2LEAF1
    - profile: TENANT_A_B_C
      server_ports:
      - Eth2
      switch_ports:
      - Ethernet3
      switches:
      - DC1-L2LEAF2
    rack: RackB

  # server-1:
  #   rack: RackB
  #   adapters:
  #     - server_ports: [ Eth1 ]
  #       switch_ports: [ Ethernet3 ]
  #       switches: [ DC1-L2LEAF1A ]
  #       profile: TENANT_A_OPZone
  #     - server_ports: [ Eth2, Eth3 ]
  #       switch_ports: [ Ethernet8, Ethernet8 ]
  #       switches: [ DC1-LEAF2A, DC1-LEAF2B ]
  #       profile: TENANT_A_ALL
  #       port_channel:
  #         state: present
  #         description: PortChanne1
  #         mode: active