---
# tasks file for eos-config-deploy-cvp - state=absent
- name: 'Collecting facts from CVP {{ inventory_hostname }}.'
  tags: [reset]
  arista.cvp.cv_facts:
  register: CVP_FACTS

- name: "Reset devices from {{ inventory_hostname }}"
  tags: [reset]
  arista.cvp.cv_device:
    devices: "{{ CVP_DEVICES }}"
    cvp_facts: '{{ CVP_FACTS.ansible_facts }}'
    device_filter: ['{{ device_filter }}']
    state: absent
  register: devices_result

- name: "Execute pending tasks on {{ inventory_hostname }}"
  tags: [reset]
  arista.cvp.cv_task:
    tasks: "{{ devices_result.data.tasks }}"
    wait: 720

- name: 'Refreshing facts from CVP {{ inventory_hostname }}.'
  tags: [reset]
  arista.cvp.cv_facts:
  register: CVP_FACTS

- name: "Deleting Containers topology on {{ inventory_hostname }}"
  tags: [reset]
  arista.cvp.cv_container:
    topology: '{{ CVP_CONTAINERS }}'
    cvp_facts: '{{ CVP_FACTS.ansible_facts }}'
    mode: delete

- name: 'Delete configlets from CVP {{ inventory_hostname }}.'
  tags: [reset]
  arista.cvp.cv_configlet:
    cvp_facts: "{{ CVP_FACTS.ansible_facts }}"
    configlets: "{{ CVP_VARS.CVP_CONFIGLETS }}"
    configlet_filter: ["{{ configlets_prefix }}"]
    state: absent
