## Ansible Generated ##

### DC1-SPINE1 ###

### Spine Info ###
switch_platform: vEOS-LAB
switch_mgmt_ip: 192.168.111.31/24

service_routing_protocols_model: multi-agent
ip_routing: true

### Hardware Counters
hardware_counters:

### Daemon TerminAttr ###
daemon_terminattr:
  ingestgrpcurl:
    ips:
      - 192.168.111.43
    port: 9910
  ingestauth_key: magickey
  ingestvrf: MGMT
  smashexcludes: "ale,flexCounter,hardware,kni,pulse,strata"
  ingestexclude: "/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"

vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
### Event Monitor ###
event_monitor:

### Event Handler ###
event_handlers:

### Load Interval ###
load_interval:

### Queue Monitor Lenght ###
queue_monitor_length:

### Name Servers ###
name_server:
  source:
    vrf: MGMT
  nodes:
    - 192.168.111.45

### NTP Servers ###
ntp_server:
  local_interface:
    vrf: MGMT
    interface: Management1
  nodes:
    - 192.168.111.45

### Redundancy ###
redundancy:

### Spanning-tree ###
spanning_tree:
  mode: none


### AAA authorization ###
aaa_authorization:
  exec_default: group tacacs+ local

### local users ###
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$kHbbE9/L.GrNTtl0$YnmI7ytA.5OtiR.z8HCPNo48NPxufpzNeQPNDBe7TOp3jdrQuwbWJPkcIIlgTUk1JEliJYvPkMKQBOn3oRC960
  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: $6$g7vDU1eTXmx3UNVm$vbD3LzxM/sSXAvzLVbJh27ni0hCw3rYWBX0gfj3QWl1.KmBBf9ZzlqEX2Tcz13I51WqXfvGUoPRhuDZ712PK7.

### Clock Timezone ###
clock:


### VRFs ###
vrfs:
  MGMT:
    ip_routing: False
### bfd multihop ###
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3

### Ethernet Interfaces ###
ethernet_interfaces:
  Ethernet6:
    peer: DC1-GW1A
    peer_interface: Ethernet1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-GW1A_Ethernet1
    mtu: 1600
    type: routed
    ip_address: 10.1.0.32/31
  Ethernet7:
    peer: DC1-GW1B
    peer_interface: Ethernet1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-GW1B_Ethernet1
    mtu: 1600
    type: routed
    ip_address: 10.1.0.40/31
  Ethernet1:
    peer: DC1-LEAF1A
    peer_interface: Ethernet1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-LEAF1A_Ethernet1
    mtu: 1600
    type: routed
    ip_address: 10.1.0.0/31
  Ethernet2:
    peer: DC1-LEAF1B
    peer_interface: Ethernet1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-LEAF1B_Ethernet1
    mtu: 1600
    type: routed
    ip_address: 10.1.0.8/31
  Ethernet3:
    peer: DC1-LEAF2A
    peer_interface: Ethernet1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-LEAF2A_Ethernet1
    mtu: 1600
    type: routed
    ip_address: 10.1.0.16/31
  Ethernet4:
    peer: DC1-LEAF2B
    peer_interface: Ethernet1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-LEAF2B_Ethernet1
    mtu: 1600
    type: routed
    ip_address: 10.1.0.24/31


### Loopback Interfaces ###
loopback_interfaces:
  Loopback0:
    description: EVPN_Overlay_Peering
    ip_address: 10.1.1.1/32


### Management Interfaces ###
management_interfaces:
  Management1:
    description: oob_management
    vrf: MGMT
    ip_address: 192.168.111.31/24
    gateway: 192.168.111.1

### TCAM Profiles ###
tcam_profile:

### MAC address table ###
mac_address_table:

### static routes ###
static_routes:
  - vrf: MGMT
    destination_address_prefix: 0.0.0.0/0
    gateway: 192.168.111.1

### prefix-lists ###
prefix_lists:
  PL-LOOPBACKS-EVPN-OVERLAY:
    sequence_numbers:
      10:
        action: "permit 10.1.1.0/24 le 32"


### route-maps ###
route_maps:
  RM-CONN-2-BGP:
    sequence_numbers:
      10:
        type: permit
        match:
          - "ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY"


### peer-filters ###
peer_filters:


### Routing - BGP ###
router_bgp:
  as: 65100
  router_id: 10.1.1.1
  bgp_defaults:
    - update wait-for-convergence
    - distance bgp 20 200 200
    - no bgp default ipv4-unicast
    - maximum-paths 2 ecmp 2
  peer_groups:
    IPv4-UNDERLAY-PEERS:
      type: ipv4
      peer_filter: LEAF-AS-RANGE
      password: "AQQvKeimxJu+uGQ/yYvv9w=="
      maximum_routes: 12000
    EVPN-OVERLAY-PEERS:
      type: evpn
      peer_filter: LEAF-AS-RANGE
      next_hop_unchanged: true
      update_source: Loopback0
      bfd: true
      ebgp_multihop: 3
      password: "q+VNViP5i4rVjW1cxFv2wA=="
      send_community: true
      maximum_routes: 0
  neighbors:
    10.1.0.33:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: 65103
    10.1.1.7:
      peer_group: EVPN-OVERLAY-PEERS
      remote_as: 65103
    10.1.0.41:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: 65103
    10.1.1.8:
      peer_group: EVPN-OVERLAY-PEERS
      remote_as: 65103
    10.1.0.1:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: 65101
    10.1.1.3:
      peer_group: EVPN-OVERLAY-PEERS
      remote_as: 65101
    10.1.0.9:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: 65101
    10.1.1.4:
      peer_group: EVPN-OVERLAY-PEERS
      remote_as: 65101
    10.1.0.17:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: 65102
    10.1.1.5:
      peer_group: EVPN-OVERLAY-PEERS
      remote_as: 65102
    10.1.0.25:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: 65102
    10.1.1.6:
      peer_group: EVPN-OVERLAY-PEERS
      remote_as: 65102
  redistribute_routes:
    connected:
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
      IPv4-UNDERLAY-PEERS:
        activate: false
      EVPN-OVERLAY-PEERS:
        activate: true
  address_family_ipv4:
    peer_groups:
      IPv4-UNDERLAY-PEERS:
        activate: true
      EVPN-OVERLAY-PEERS:
        activate: false

### Routing - OSPF ###
router_ospf:

### Routing - ISIS ###
router_isis:

### Queue Monitor Streaming ###
queue_monitor_streaming:

### Management API http ###
management_api_http:
  enable_https: True
  enable_vrfs:
    MGMT:
